import { useEffect, useRef, useState } from "react";
import { api } from "./api.js";
import DataTable from "./DataTable.jsx";
import Dialog from "./Dialog.jsx";
import Pagination from "./Pagination.jsx";
import MoreActions from "./MoreActions.jsx";
import TextInspector from "./TextInspector.jsx";
import { Icon } from "./Icon.jsx";
import { useWords, Section } from "./LifecycleViews.jsx";
import { formatDate } from "./analysisView.js";
import { validationDataError } from "./validationData.js";
import DatasetRevisionBrowser from "./DatasetRevisionBrowser.jsx";
import EvaluationDatasetCatalog, { ProductionEvaluationBadge } from "./EvaluationDatasetCatalog.jsx";
import { initialDatasetList } from "./evaluationDatasets.js";

const states = { ready: ["포함 가능", "Ready to Include"], needs_attention: ["확인 필요", "Needs attention"], excluded: ["제외", "Excluded"] };
const changes = { added: ["추가", "Added"], changed: ["수정", "Changed"], removed: ["삭제", "Removed"], unchanged: ["변경 없음", "Unchanged"] };
const verdicts = { true_positive: ["정탐", "True positive"], false_positive: ["오탐", "False positive"], inconclusive: ["보류", "Inconclusive"] };
const issues = { reference_verdict_missing: ["기대 판정을 입력하세요.", "Add an expected verdict."], reference_conflict: ["같은 입력을 다시 가져오는 중 기대 판정 또는 내부 전용 조건이 달랐습니다. 원본 분석의 기대 판정을 확인하고 저장하세요.", "An import has a different expected verdict or internal-data restriction for this input. Check the source and save the confirmed verdict."], reference_verdict_required: ["기대 판정을 입력하세요.", "Add an expected verdict."], event_invalid: ["입력 필드의 형식과 필수 값을 확인하세요.", "Check input types and required fields."], event_schema_invalid: ["저장된 입력 스키마의 제한을 확인하세요.", "Check the saved input schema constraints."] };
const referenceOrigins = { published_ground_truth: ["공식 버전", "Published Version"], reference_label: ["참고 판정", "Reference Verdict"], manual: ["직접 입력", "Manual"], none: ["없음", "None"] };
const initialQuery = { query: "", limit: 50, offset: 0 };

function DraftEditor({ item, busy, onSave, onDirty }) {
  const w = useWords();
  const make = value => ({ event: JSON.stringify(value?.event || {}, null, 2), reference_verdict: value?.reference_verdict || "", comment: value?.comment || "", case_name: value?.case_name || "", difficulty: value?.difficulty || "", test_category: value?.test_category || "", tags: (value?.tags || []).join(", "), excluded: value?.excluded || false });
  const [form, setForm] = useState(() => make(item)), [error, setError] = useState("");
  const dirty = JSON.stringify(form) !== JSON.stringify(make(item));
  useEffect(() => { onDirty(dirty); return () => onDirty(false); }, [dirty, onDirty]);
  const change = key => event => setForm(value => ({ ...value, [key]: event.target.value }));
  async function save(event) {
    event.preventDefault(); setError("");
    let input;
    try { input = JSON.parse(form.event); if (!input || Array.isArray(input) || typeof input !== "object") throw new Error(); }
    catch { setError(w("입력은 JSON 객체로 작성하세요.", "Input must be a JSON object.")); return; }
    await onSave({ ...form, event: input, reference_verdict: form.reference_verdict || null,
      tags: [...new Set(form.tags.split(",").map(v => v.trim()).filter(Boolean))],
      difficulty: form.difficulty || null, test_category: form.test_category || null, case_name: form.case_name || null });
  }
  if (item?.change === "removed") return <><p>{w("최근 공식 버전에서 삭제한 문항입니다. 되돌리면 초안에 다시 추가됩니다.", "This case was removed from the draft. Revert to restore its published content.")}</p><TextInspector label={w("발행 당시 입력", "Published input")} value={item.event} /></>;
  return <form className="data-form r3-draft-editor" onSubmit={save}>
    {item?.reference_origin && <p className="v5-context">{w("기대 판정 출처", "Expected Verdict Origin")}: {({ published_ground_truth: w("공식 버전", "Published Version"), reference_label: w("참고 판정", "Reference Verdict"), manual: w("직접 입력", "Manual"), none: w("없음", "None") })[item.reference_origin]}</p>}
    {item?.internal_only && <p className="notice">{w("운영에서 가져온 문항 · 내부 vLLM 전용", "Imported from Production · internal vLLM only")}</p>}
    {item?.original_analysis_deleted && <p className="v5-context">{w("원본 분석은 삭제됐으며 이 사본은 보존됐습니다.", "The source analysis was deleted; this copy is preserved.")}</p>}
    {item?.issues?.length > 0 && <ul className="r3-issues">{item.issues.map((issue, index) => <li key={index}>{issues[issue.code] ? w(...issues[issue.code]) : w("입력을 확인하세요.", "Check the input.")}</li>)}</ul>}
    <fieldset disabled={busy} className="data-form"><label>{w("문항명", "Case name")}<input maxLength={240} value={form.case_name} onChange={change("case_name")} placeholder={w("공격 유형이나 확인할 내용", "Attack type or scenario")} /></label>
      <div className="r3-field-pair"><label>{w("기대 판정", "Expected Verdict")}<select value={form.reference_verdict} onChange={change("reference_verdict")}><option value="">{w("기대 판정 없음", "No expected verdict")}</option>{Object.entries(verdicts).map(([key, words]) => <option key={key} value={key}>{w(...words)}</option>)}</select></label><label>{w("포함 여부", "Inclusion")}<select value={form.excluded ? "exclude" : "include"} onChange={e => setForm(v => ({ ...v, excluded: e.target.value === "exclude" }))}><option value="include">{w("자동 검사 후 포함", "Include when ready")}</option><option value="exclude">{w("평가에서 제외", "Exclude from evaluation")}</option></select></label></div>
      <label>{w("입력 JSON", "Input JSON")}<textarea className="r3-code-input" rows={13} value={form.event} onChange={change("event")} spellCheck={false} placeholder={'{"event_id": "…", "payload": "…"}'} /></label>
      <label>{w("판단 이유", "Verdict rationale")}<textarea rows={3} maxLength={4000} value={form.comment} onChange={change("comment")} placeholder={w("기대 판정을 정한 근거", "Why this verdict is expected")} /></label>
      <div className="r3-field-pair"><label>{w("유형", "Category")}<input maxLength={120} value={form.test_category} onChange={change("test_category")} /></label><label>{w("난이도", "Difficulty")}<input maxLength={80} value={form.difficulty} onChange={change("difficulty")} /></label></div>
      <label>{w("태그", "Tags")}<input value={form.tags} onChange={change("tags")} placeholder={w("쉼표로 구분", "Separate with commas")} /></label>
    </fieldset>
    <p className="v5-context">{w("기대 판정과 메모는 모델에 전달하지 않습니다. 저장해도 공식 버전과 이전 평가는 바뀌지 않습니다.", "Expected verdicts and notes never enter model inputs. Saving does not change Published Versions or past evaluations.")}</p>
    {error && <p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{w("초안 저장", "Save draft")}</button>
  </form>;
}

export default function GroundTruthWorkspace({ id, onSelect, initialState, initialCaseId, listState, onListStateChange }) {
  const w = useWords(); const [localListState, setLocalListState] = useState(initialDatasetList);
  const catalogState = listState || localListState, setCatalogState = onListStateChange || setLocalListState;
  const [data, setData] = useState(null), [query, setQuery] = useState({ ...initialQuery, ...(initialState ? { state: initialState } : {}) }), [search, setSearch] = useState("");
  const [revision, refresh] = useState(0), [item, setItem] = useState(null), [selection, setSelection] = useState([]), [dirty, setDirty] = useState(false);
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [modal, setModal] = useState(null), [ack, setAck] = useState(false), [notice, setNotice] = useState("");
  const [name, setName] = useState(""), [description, setDescription] = useState(""), [bulkValue, setBulkValue] = useState("");
  const pending = useRef(false), detailPane = useRef(null), caseTrigger = useRef(null);
  useEffect(() => {
    if (!window.matchMedia("(max-width: 1050px)").matches) return;
    if (item) { detailPane.current?.focus({ preventScroll: true }); detailPane.current?.scrollIntoView({ block: "start" }); }
    else if (caseTrigger.current?.isConnected) caseTrigger.current.focus({ preventScroll: true });
  }, [item?.item_id, Boolean(item)]);
  const [productionGroundTruth, setProductionGroundTruth] = useState(null);
  const [productionError, setProductionError] = useState(false);
  useEffect(() => { const controller = new AbortController(); setProductionGroundTruth(null); setProductionError(false); api.productionConfiguration({ signal: controller.signal }).then(value => { if (!controller.signal.aborted) setProductionGroundTruth(value.evaluation?.summary?.ground_truth || null); }).catch(() => { if (!controller.signal.aborted) setProductionError(true); }); return () => controller.abort(); }, [revision]);
  useEffect(() => { setQuery({ ...initialQuery, ...(initialState ? { state: initialState } : {}) }); setSearch(""); setItem(null); setSelection([]); setData(null); setError(""); }, [id, initialState]);
  useEffect(() => { if (!id) return; const controller = new AbortController(); setError(""); api.workingDataset(id, query, { signal: controller.signal }).then(value => { if (!controller.signal.aborted) { setData(value); setSelection([]); } }).catch(e => { if (!controller.signal.aborted) setError(validationDataError(e)); }); return () => controller.abort(); }, [id, query, revision]);
  useEffect(() => { if (!id || !initialCaseId) return; const controller = new AbortController(); api.workingItem(id, initialCaseId, { signal: controller.signal }).then(value => { if (!controller.signal.aborted) setItem(value); }).catch(() => { if (!controller.signal.aborted) setError(w("연결된 문항이 초안에 없습니다. 공식 버전 이력을 확인하세요.", "The linked case is not in the Draft. Inspect Published Version history.")); }); return () => controller.abort(); }, [id, initialCaseId]);
  useEffect(() => { if (!dirty) return; const leave = event => { event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", leave); return () => window.removeEventListener("beforeunload", leave); }, [dirty]);
  async function action(callback, close = true) { if (pending.current) return; pending.current = true; setBusy(true); setError(""); try { await callback(); if (close) { setModal(null); setItem(null); } refresh(n => n + 1); } catch (e) { setError(validationDataError(e)); } finally { pending.current = false; setBusy(false); } }
  const expected = { expected_working_revision: data?.working_revision };
  const locked = busy || dirty;
  const pageCases = data?.items.filter(i => i.change !== "removed").map(i => i.item_id) || [];
  function selectDataset(value) { if (dirty) { setModal({ kind: "unsaved", nextId: value }); return; } onSelect(value); }
  function bulk(actionName) { setBulkValue(""); setModal({ kind: "bulk", action: actionName }); }
  async function openItem(caseId) { caseTrigger.current = document.activeElement; await action(async () => { setItem(await api.workingItem(id, caseId)); }, false); }
  const omitted = (data?.counts.needs_attention || 0) + (data?.counts.excluded || 0);
  return <div className="page-stack r3-ground-truth">
    {id && <div className="dataset-detail-toolbar"><button type="button" className="back" disabled={busy} onClick={() => selectDataset(null)}>← {w("평가 데이터셋", "Evaluation Datasets")}</button><button className="secondary" disabled={locked} onClick={() => refresh(n => n + 1)}>{w("새로고침", "Refresh")}</button>{data && <><MoreActions disabled={locked} label={w("평가 데이터셋 관리", "Manage Evaluation Dataset")}><button onClick={() => { setName(data.name); setDescription(data.description); setModal({ kind: "rename" }); }}>{w("이름·설명 수정", "Edit name and description")}</button><button onClick={() => action(async () => { const history = await api.validationDataset(id); setModal({ kind: "history", history }); }, false)}>{w("발행·이전 버전", "Published & legacy history")}</button><button disabled={!data.latest_published_revision_id} onClick={() => setModal({ kind: "discard" })}>{w("초안 변경 모두 되돌리기", "Discard draft changes")}</button><button onClick={() => setModal({ kind: "delete" })}>{w("평가 데이터셋 삭제", "Delete Evaluation Dataset")}</button></MoreActions><button className="primary" disabled={locked || !data.counts.ready} onClick={() => { setAck(false); setModal({ kind: "publish" }); }}>{w("공식 버전 만들기", "Publish Version")}</button></>}</div>}
    {productionError && <p className="notice" role="status">{w("현재 운영 평가 정보를 불러오지 못해 사용 버전을 표시하지 않습니다.", "Current Production Evaluation is unavailable; its dataset version is not shown.")} <button type="button" className="text-button" onClick={() => refresh(value => value + 1)}>{w("다시 조회", "Retry")}</button></p>}
    {notice && <p role="status" className="notice">{notice}</p>}{error && <p role="alert" className="error">{error}</p>}
    {!id ? <EvaluationDatasetCatalog state={catalogState} onChange={setCatalogState} onSelect={selectDataset} onCreate={() => { setName(""); setDescription(""); setModal({ kind: "create" }); }} groundTruth={productionGroundTruth} revision={revision} disabled={locked} /> : !data ? (error ? null : <p role="status">{w("초안 조회 중…", "Loading draft…")}</p>) : <>
      <section className="panel dataset-detail-summary"><div><div className="dataset-draft-heading"><h2>{data.name}</h2><ProductionEvaluationBadge datasetId={data.id} groundTruth={productionGroundTruth} /></div>{data.description && <p className="v5-context">{data.description}</p>}</div><dl><div><dt>{w("초안", "Draft")}</dt><dd>{data.total} {w("문항", "cases")} · {w("확인 필요", "Needs attention")} {data.counts.needs_attention} · {w("변경", "Changes")} {data.working_changes_count}</dd><dd className="ux-muted">{w("추가", "Added")} {data.changes.added} · {w("수정", "Changed")} {data.changes.changed} · {w("삭제", "Removed")} {data.changes.removed}</dd></div><div><dt>{w("최근 공식 버전", "Latest Published Version")}</dt><dd>{data.published_revisions[0] ? `r${data.published_revisions[0].revision} · ${data.published_revisions[0].total} ${w("문항", "cases")}` : w("미발행", "Not published")}</dd></div></dl></section>
      <div className="r3-ground-truth-split"><Section className="r3-case-list" title={w("초안", "Draft")} action={<button className="secondary" disabled={locked} onClick={() => setItem({ event: {} })}>+ {w("문항", "Case")}</button>}>
        <div className="r3-state-filters" role="group" aria-label={w("문항 상태", "Case state")}>{[["", ["전체", "All"]], ...Object.entries(states)].map(([key, words]) => <button key={key} className={`r3-state-filter ${key}`} aria-pressed={(query.state || "") === key} disabled={locked} onClick={() => setQuery(v => ({ ...v, state: key || undefined, offset: 0 }))}>{w(...words)} <strong>{key ? data.counts[key] : data.total}</strong></button>)}</div>
        <form className="r3-case-filters" onSubmit={e => { e.preventDefault(); setQuery(v => ({ ...v, query: search.trim(), offset: 0 })); }}><input aria-label={w("문항 검색", "Find case")} value={search} maxLength={240} disabled={locked} onChange={e => setSearch(e.target.value)} placeholder={w("문항명·유형·태그", "Case, category or tag")} /><select aria-label={w("변경 구분", "Working change")} value={query.change || ""} disabled={locked} onChange={e => setQuery(v => ({ ...v, change: e.target.value || undefined, offset: 0 }))}><option value="">{w("모든 변경", "All changes")}</option>{Object.entries(changes).map(([key, words]) => <option key={key} value={key}>{w(...words)}</option>)}</select><select aria-label={w("기대 판정 필터", "Expected verdict filter")} value={query.reference_verdict || ""} disabled={locked} onChange={e => setQuery(v => ({ ...v, reference_verdict: e.target.value || undefined, offset: 0 }))}><option value="">{w("모든 기대 판정", "All expected verdicts")}</option>{Object.entries(verdicts).map(([key, words]) => <option key={key} value={key}>{w(...words)}</option>)}</select><select aria-label={w("기대 판정 출처", "Expected verdict source")} value={query.reference_origin || ""} disabled={locked} onChange={e => setQuery(v => ({ ...v, reference_origin: e.target.value || undefined, offset: 0 }))}><option value="">{w("모든 출처", "All sources")}</option>{Object.entries(referenceOrigins).map(([key, words]) => <option key={key} value={key}>{w(...words)}</option>)}</select><button className="secondary" disabled={locked}>{w("검색", "Search")}</button></form>
        {selection.length > 0 && <div className="r3-bulk-bar"><span>{selection.length} {w("선택", "selected")}</span>{[["include", "포함", "Include"], ["exclude", "제외", "Exclude"], ["tag", "태그", "Tag"], ["categorize", "유형", "Category"], ["delete", "삭제", "Delete"]].map(([key, ko, en]) => <button className="text-button" key={key} disabled={locked} onClick={() => bulk(key)}>{w(ko, en)}</button>)}</div>}
        <DataTable label={w("평가 데이터셋 문항", "Evaluation Dataset cases")} data={data.items} columns={[
          { id: "selection", width: 40, header: <input type="checkbox" aria-label={w("현재 페이지 전체 선택", "Select current page")} disabled={locked || !pageCases.length} checked={pageCases.length > 0 && pageCases.every(v => selection.includes(v))} onChange={e => setSelection(e.target.checked ? pageCases : [])} />, render: row => row.change !== "removed" && <input type="checkbox" aria-label={`${row.case_name || w("문항", "Case")} ${w("선택", "select")}`} disabled={locked} checked={selection.includes(row.item_id)} onChange={e => setSelection(v => e.target.checked ? [...v, row.item_id] : v.filter(i => i !== row.item_id))} /> },
          { id: "case", header: w("문항", "Case"), render: row => <><button className="text-button" disabled={locked} onClick={() => openItem(row.item_id)}>{row.case_name || w("이름 없는 문항", "Untitled case")}</button><small>{row.test_category || w("미분류", "Uncategorized")} · {w(...changes[row.change])}</small></> },
          { id: "answer", header: w("기대 판정", "Expected Verdict"), render: row => row.reference_verdict ? w(...verdicts[row.reference_verdict]) : "—" },
          { id: "origin", header: w("기대 판정 출처", "Expected Verdict Origin"), render: row => ({ published_ground_truth: w("공식 버전", "Published Version"), reference_label: w("참고 판정", "Reference Verdict"), manual: w("직접 입력", "Manual"), none: w("없음", "None") })[row.reference_origin] || "—" },
          { id: "state", header: w("상태", "State"), render: row => <span className={`r3-badge ${row.state}`}>{w(...states[row.state])}</span> },
        ]} empty={w("조건에 맞는 문항이 없습니다.", "No cases match these filters.")} />
        <Pagination total={data.filtered_total} limit={query.limit} offset={query.offset} disabled={locked} onOffsetChange={offset => setQuery(v => ({ ...v, offset }))} />
      </Section><aside ref={detailPane} tabIndex={-1} aria-label={w("문항 상세", "Case details")} className="r3-case-detail"><div className="v5-section-head"><h2>{w("문항 상세", "Case details")}</h2>{item && <button className="icon-button" disabled={busy} aria-label={w("문항 상세 닫기", "Close case details")} onClick={() => dirty ? setModal({ kind: "unsaved" }) : setItem(null)}><Icon name="close" size={18} /></button>}</div>{item ? <><DraftEditor key={item.item_id || "new"} item={item} busy={busy} onDirty={setDirty} onSave={payload => action(async () => { await api.saveWorkingItem(id, item.item_id, { ...expected, ...payload }); setNotice(w("초안을 저장했습니다.", "Draft saved.")); })} />{item.item_id && item.change === "added" && <button className="text-button" disabled={locked} onClick={() => setModal({ kind: "discard_added", caseId: item.item_id })}>{w("추가 취소", "Discard addition")}</button>}{item.item_id && item.change !== "added" && data.latest_published_revision_id && <button className="text-button" disabled={locked} onClick={() => setModal({ kind: "revert", caseId: item.item_id })}>{item.change === "removed" ? w("문항 복원", "Restore case") : w("공식 버전으로 되돌리기", "Revert to Published Version")}</button>}</> : <div className="r3-empty-detail"><Icon name="test" size={28} /><p>{w("문항을 선택하면 입력과 기대 판정을 함께 볼 수 있습니다.", "Select a case to inspect its input and expected verdict.")}</p></div>}</aside></div>
    </>}
    <Dialog open={Boolean(modal)} title={modal?.kind === "publish" ? w("공식 버전 만들기", "Publish Version") : modal?.kind === "history" ? w("발행·이전 버전", "Published & legacy history") : w("변경 확인", "Confirm change")} onClose={() => { if (!busy) setModal(null); }}>
      {modal && ["create", "rename"].includes(modal.kind) && <form className="data-form" onSubmit={e => { e.preventDefault(); action(async () => { const result = modal.kind === "create" ? await api.createValidationDataset({ name, description }) : await api.updateWorkingMetadata(id, { name, description, ...expected }); onSelect(result.id); }); }}><label>{w("평가 데이터셋 이름", "Evaluation Dataset name")}<input required value={name} maxLength={120} onChange={e => setName(e.target.value)} /></label><label>{w("설명", "Description")}<textarea value={description} maxLength={1000} onChange={e => setDescription(e.target.value)} /></label><button className="primary" disabled={busy}>{w("저장", "Save")}</button></form>}
      {modal?.kind === "publish" && <><p>{w("이 시점의 준비된 문항과 기대 판정을 고정합니다. 이후 초안을 수정해도 이 리비전은 바뀌지 않습니다.", "Freezes ready cases and expected verdicts. Later draft edits do not change this revision.")}</p><dl className="v5-facts"><div><dt>{w("초안 전체", "Working total")}</dt><dd>{data.total}</dd></div><div><dt>{w("평가에 포함", "Included")}</dt><dd>{data.counts.ready}</dd></div><div><dt>{w("확인 필요 / 제외", "Needs attention / excluded")}</dt><dd>{data.counts.needs_attention} / {data.counts.excluded}</dd></div><div><dt>{w("포함 비율", "Inclusion rate")}</dt><dd>{data.total ? (data.counts.ready / data.total * 100).toFixed(1) : 0}%</dd></div></dl><h3>{w("포함할 기대 판정의 출처", "Included reference origins")}</h3><dl className="r5-counts">{Object.entries(data.included_reference_origin_counts || {}).map(([key, count]) => <div key={key}><dt>{({ manual: w("직접 입력", "Manual"), reference_label: w("참고 판정", "Reference Verdict"), published_ground_truth: w("공식 버전", "Published Version"), none: w("없음", "None") })[key] || key}</dt><dd>{count}</dd></div>)}</dl><p className="v5-context">{w("포함 가능은 필수 입력과 기대 판정 검사를 통과했다는 뜻입니다. 사람이 정답을 승인했다는 뜻은 아닙니다.", "Ready to Include means validation passed. It is not human approval of verdict correctness.")}</p>{omitted > 0 && <label className="checkbox-row"><input type="checkbox" checked={ack} onChange={e => setAck(e.target.checked)} />{w(`${omitted}문항이 빠지는 것을 확인했습니다.`, `I acknowledge that ${omitted} cases will be omitted.`)}</label>}<button className="primary" disabled={busy || omitted > 0 && !ack} onClick={() => action(async () => { const result = await api.publishDataset(id, { ...expected, acknowledge_exclusions: ack }); setNotice(w(`r${result.revision}을 발행했습니다.`, `Published r${result.revision}.`)); })}>{w("발행", "Publish")}</button></>}
      {modal?.kind === "discard_added" && <><p>{w("이 문항의 추가를 취소합니다. 공식 버전은 바뀌지 않습니다.", "Discard this added case. Published Versions are unchanged.")}</p><button className="danger" disabled={busy} onClick={() => action(() => api.workingBulk(id, { ...expected, case_ids: [modal.caseId], action: "delete" }))}>{w("추가 취소", "Discard addition")}</button></>}
      {modal?.kind === "bulk" && <><p>{selection.length} {w("문항을 변경합니다. 공식 버전은 유지됩니다.", "cases will change. Published Versions remain unchanged.")}</p>{["tag", "categorize"].includes(modal.action) && <label>{w("적용할 값", "Value")}<input maxLength={120} value={bulkValue} onChange={e => setBulkValue(e.target.value)} /></label>}<button className={modal.action === "delete" ? "danger" : "primary"} disabled={busy} onClick={() => action(() => api.workingBulk(id, { ...expected, case_ids: selection, action: modal.action, test_category: bulkValue || null, tags: bulkValue.split(",").map(v => v.trim()).filter(Boolean) }))}>{w("적용", "Apply")}</button></>}
      {modal && ["revert", "discard", "delete"].includes(modal.kind) && <><p>{modal.kind === "delete" ? w("평가 데이터셋을 목록에서 삭제합니다. 기존 분석·평가·발행 이력은 보존합니다.", "Removes the dataset from the list. Analyses, evaluations and revision history are retained.") : w("최근 공식 버전의 내용으로 되돌립니다. 초안에서 수정하거나 추가한 내용은 사라집니다.", "Restores the latest published content. Unsaved working additions and changes will be discarded.")}</p><button className="danger" disabled={busy} onClick={() => action(async () => { if (modal.kind === "delete") { await api.deleteValidationDataset(id, data.revision); onSelect(null); } else await api.restoreWorking(id, modal.caseId, expected); })}>{w("확인", "Confirm")}</button></>}
      {modal?.kind === "unsaved" && <><p>{w("아직 저장하지 않은 수정 내용을 버릴까요?", "Discard your unsaved edits?")}</p><button className="secondary" onClick={() => setModal(null)}>{w("계속 작성", "Keep editing")}</button><button className="danger" onClick={() => { setItem(null); setModal(null); if (Object.hasOwn(modal, "nextId")) onSelect(modal.nextId); }}>{w("버리기", "Discard")}</button></>}
      {modal?.kind === "history" && <><p className="v5-context">{w("이전 문항별 승인 기록은 보존하지만 새 공식 평가로 소급 인정하지 않습니다.", "Legacy review records are retained, but are not retroactively published for official evaluation.")}</p><DataTable label={w("리비전 이력", "Revision history")} data={modal.history.versions} columns={[{ id: "revision", header: w("리비전", "Revision"), render: row => `r${row.revision}` }, { id: "kind", header: w("종류", "Kind"), render: row => data.published_revisions.some(v => v.id === row.id) ? w("발행됨", "Published") : w("이전 기록", "Legacy") }, { id: "total", header: w("문항", "Cases") }, { id: "created_at", header: w("시각", "Time"), render: row => formatDate(row.created_at) }]} /><DatasetRevisionBrowser datasetId={id} versions={modal.history.versions} /></>}
      {error && <p className="error" role="alert">{error}</p>}
    </Dialog>
  </div>;
}
