import { useEffect, useRef, useState } from "react";
import { api } from "./api.js";
import { FIELD_TYPES, SAMPLE_EVENT, changeFieldType, createSchemaSettingsController, draftPayload, editSchemaField, emptySchemaSettingsState, newSchemaField, schemaDraft, schemaFieldDiff, schemaVersionName } from "./inputSchemaSettings.js";
import "./inputSchemaSettings.css";

const timestamp = value => value ? new Date(value).toLocaleString("ko-KR") : "미기록";
const constraintNames = { min_length: "최소 글자 수", max_length: "최대 글자 수", minimum: "최솟값", maximum: "최댓값", min_items: "최소 항목 수", max_items: "최대 항목 수" };
export function SchemaFields({ fields = [] }) {
  return <div className="table-wrap schema-field-table"><table><caption className="sr-only">입력 필드 정의</caption><thead><tr><th scope="col">필드 / 설명</th><th scope="col">타입</th><th scope="col">필수 / null</th><th scope="col">제한</th></tr></thead><tbody>{fields.map(field => <tr key={field.name}><td><code>{field.name}</code><p>{field.description || "설명 없음"}</p></td><td>{field.type}</td><td>{field.required ? "필수" : "선택"}<br />{field.nullable ? "null 허용" : "null 불가"}</td><td>{Object.entries(constraintNames).filter(([key]) => field[key] != null).map(([key, label]) => <div key={key}>{label}: {field[key]}</div>)}{field.enum != null && <div>허용값: <code>{JSON.stringify(field.enum)}</code></div>}{(field.items || field.properties) && <details><summary>하위 필드 정의</summary><pre>{JSON.stringify(field.items || field.properties, null, 2)}</pre></details>}</td></tr>)}</tbody></table></div>;
}
export function SchemaDiff({ before, after, beforeLabel = "현재 적용 버전", afterLabel = "선택한 버전" }) {
  const changes = schemaFieldDiff(before, after);
  return <div className="schema-diff" aria-label="필드 정의 변경 비교"><p>{beforeLabel} → {afterLabel} · 설명·타입·필수 여부·제한을 비교합니다.</p>{changes.length ? changes.map(change => <details key={change.name}><summary><span>{({ added: "추가", removed: "삭제", changed: "변경" })[change.kind]}</span> <code>{change.name}</code></summary><div className="schema-diff-columns"><div><h4>변경 전</h4><pre>{change.before ? JSON.stringify(change.before, null, 2) : "필드 없음"}</pre></div><div><h4>변경 후</h4><pre>{change.after ? JSON.stringify(change.after, null, 2) : "필드 없음"}</pre></div></div></details>) : <p className="muted">필드 정의에 차이가 없습니다.</p>}</div>;
}
function FieldEditor({ field, index, defaults, disabled, onChange, onRemove }) {
  const baseline = defaults.find(value => value.name === field.name);
  const numericKeys = field.type === "string" ? ["min_length", "max_length"] : ["integer", "number"].includes(field.type) ? ["minimum", "maximum"] : field.type === "array" ? ["min_items", "max_items"] : [];
  return <details className="schema-field-editor" open={!baseline}><summary><code>{field.name || `새 필드 ${index + 1}`}</code><span>{baseline ? "기본 필드 · 이름/타입 보호" : "추가 필드"}</span></summary><fieldset disabled={disabled}>
    <div className="schema-editor-grid"><label>필드명<input value={field.name} maxLength={64} readOnly={Boolean(baseline)} onChange={event => onChange({ ...field, name: event.target.value })} spellCheck={false} /></label><label>타입<select value={field.type} disabled={Boolean(baseline)} onChange={event => onChange(changeFieldType(field, event.target.value))}>{FIELD_TYPES.map(type => <option key={type}>{type}</option>)}</select></label>
      <label className="schema-full">설명<textarea rows={2} value={field.description} maxLength={1000} onChange={event => onChange({ ...field, description: event.target.value })} placeholder="필드가 나타내는 값과 수집 기준. 이 설명은 이력에만 기록합니다." /></label>
      <label className="schema-check"><input type="checkbox" checked={field.required} disabled={baseline?.required} onChange={event => onChange({ ...field, required: event.target.checked })} />필수</label><label className="schema-check"><input type="checkbox" checked={field.nullable} disabled={baseline?.nullable === false} onChange={event => onChange({ ...field, nullable: event.target.checked })} />null 허용</label>
      {numericKeys.map(key => <label key={key}>{constraintNames[key]}<input type="number" step={field.type === "number" ? "any" : "1"} min={key.startsWith("min_") || key.startsWith("max_") ? 0 : undefined} value={field[key] ?? ""} onChange={event => onChange({ ...field, [key]: event.target.value })} placeholder="제한 없음" />{baseline?.[key] != null && <small>기본 경계 {baseline[key]}보다 완화할 수 없습니다.</small>}</label>)}
      {!["object", "array"].includes(field.type) && <label className="schema-full">허용값 · JSON 배열<input value={field._enum || ""} onChange={event => onChange({ ...field, _enum: event.target.value })} placeholder={'예: ["east", "west"] / [1, 2] · 빈칸이면 지정 안 함'} spellCheck={false} /></label>}
      {field.type === "object" && <label className="schema-full">하위 필드 · properties JSON 배열<textarea rows={6} value={field._properties || ""} onChange={event => onChange({ ...field, _properties: event.target.value })} placeholder={'[{"name":"region","description":"지역","type":"string","required":false,"nullable":true}]'} spellCheck={false} /><small>각 하위 필드도 이름·타입·필수·null·제한을 정의합니다. 등록하지 않은 하위 값은 보존합니다.</small></label>}
      {field.type === "array" && <label className="schema-full">배열 항목 · items JSON 객체<textarea rows={5} value={field._items || ""} onChange={event => onChange({ ...field, _items: event.target.value })} placeholder={'{"type":"string","nullable":false,"max_length":120}'} spellCheck={false} /><small>type·nullable·타입별 제한을 지정합니다. 객체 항목은 properties로 하위 필드를 정의합니다.</small></label>}
    </div><button type="button" className="secondary" disabled={Boolean(baseline)} onClick={onRemove}>필드 삭제</button>
  </fieldset></details>;
}

export default function InputSchemaSettings() {
  const [state, setState] = useState(emptySchemaSettingsState);
  const [draft, setDraft] = useState(null); const [sample, setSample] = useState(SAMPLE_EVENT);
  const controller = useRef(null); const draftName = useRef(null);
  useEffect(() => { const instance = createSchemaSettingsController({ api, onChange: setState }); controller.current = instance; void instance.refresh(); return () => { instance.dispose(); controller.current = null; }; }, []);
  useEffect(() => { if (draft) { draftName.current?.focus(); draftName.current?.closest("form")?.scrollIntoView({ block: "start" }); } }, [Boolean(draft)]);
  const { catalog, selected, active } = state;
  const versions = catalog?.items || []; const busy = Boolean(state.busy); const blocked = busy || state.loading || state.needsRefresh || !catalog;
  let draftFields = null; let draftError = "";
  if (draft) { try { draftFields = draftPayload({ ...draft, name: draft.name || "미지정", change_note: draft.change_note || "미지정" }).fields; } catch (error) { draftError = error.message; } }
  const cloneVersion = () => { if (draft && !window.confirm("저장하지 않은 초안을 버리고 다시 복제할까요?")) return; controller.current?.clearValidation(); setDraft(schemaDraft(selected, catalog?.default_fields)); };
  const rollback = selected && active && selected.version_number < active.version_number;
  return <div className="page-stack input-schema-settings">
    <section className="panel schema-overview"><div className="schema-heading"><div><h2>입력 스키마</h2><p>WAF 이벤트의 필드와 접수 기준을 버전별로 관리합니다. 저장과 운영 적용은 별도입니다.</p></div><button type="button" className="secondary" disabled={busy || state.loading} onClick={() => controller.current?.refresh()}>목록 새로고침</button></div><p><span className="status purpose-production">운영 적용 중</span> <strong>{catalog ? schemaVersionName(active) : "조회 중…"}</strong></p><p className="schema-help">필드 설명·타입·제한은 당시 버전으로 추론 이력에 기록하며, 설명을 LLM 입력에 추가하지 않습니다. 이미 접수된 분석과 테스트는 기존 스키마를 유지합니다.</p><p className="schema-help">기본 11개 필드의 이름·타입·내부 필수 조건은 보호합니다. 사용자 추가 필드는 자유롭게 정의하되 서버 제어값과 정답 필드는 등록할 수 없습니다. 등록하지 않은 벤더 필드는 기존처럼 보존합니다.</p></section>
    <div className="notice"><p>필드 설명은 Production API와 기존 공개 Swagger 정의서에도 반영됩니다. 비밀값·실제 WAF 로그·개인정보는 설명에 넣지 마세요.</p><p>숫자·boolean·객체·배열 타입의 추가 필드를 사용한다면 JSON으로 업로드하세요. CSV는 기존 두 포트만 숫자로 변환하고 나머지 값은 문자열로 읽습니다.</p></div>
    {state.error && <div className="error" role="alert">{state.error}</div>}{state.notice && <div className="notice" role="status">{state.notice}</div>}
    <div className="schema-layout"><section className="panel schema-version-list" aria-label="입력 스키마 저장 버전"><h2>저장 버전</h2>{versions.map(version => <button type="button" key={version.id} disabled={blocked || Boolean(draft)} aria-pressed={selected?.id === version.id} onClick={() => controller.current?.select(version.id)}><strong>{schemaVersionName(version)}</strong>{version.id === catalog.active_version_id && <span>운영 적용 중</span>}<small>{timestamp(version.created_at)}</small><small>{version.change_note}</small></button>)}{!versions.length && <p>{state.loading ? "불러오는 중…" : "저장 버전 없음"}</p>}</section>
      <div className="page-stack schema-workspace">{state.loading && <p className="loading" role="status">스키마 정의를 불러오는 중…</p>}{selected && !state.loading && <section className="panel"><div className="schema-heading"><div><h2>{schemaVersionName(selected)}</h2><p>저장된 필드 정의 · 읽기 전용</p></div><button type="button" className="secondary" disabled={blocked} onClick={cloneVersion}>복제하여 새 버전 작성</button></div><p>{selected.change_note}</p><SchemaFields fields={selected.fields} /><details className="schema-identifiers"><summary>버전 식별 정보</summary><dl><dt>버전 ID</dt><dd>{selected.id}</dd><dt>필드 정의 지문</dt><dd>{selected.content_hash}</dd><dt>등록자 / 시각</dt><dd>{selected.created_by} · {timestamp(selected.created_at)}</dd><dt>복제 원본</dt><dd>{selected.parent_id || "기본 버전"}</dd></dl></details>
        <h3>현재 운영 버전과 변경 비교</h3><SchemaDiff before={active?.fields} after={selected.fields} beforeLabel={schemaVersionName(active)} afterLabel={schemaVersionName(selected)} />
        {!draft && <div className="schema-validation"><h3>합성 샘플 입력 검증</h3><p>이벤트 한 건의 JSON으로 접수 기준을 확인합니다. LLM 호출이나 분석 접수는 하지 않으며 샘플을 서버에 저장하지 않습니다. 실제 원문·Cookie·API Key는 넣지 마세요.</p><label>검증할 샘플<textarea rows={10} value={sample} disabled={busy} spellCheck={false} onChange={event => { controller.current?.clearValidation(); setSample(event.target.value); }} /></label><button type="button" className="secondary" disabled={blocked} onClick={() => controller.current?.validate(sample)}>{state.busy === "validate" ? "검증 중…" : "선택 버전으로 샘플 검증"}</button>
          {state.validation && <div role="status" className={state.validation.valid ? "notice" : "error"}>{state.validation.valid ? "샘플이 접수 기준을 통과했습니다. 이 검증은 실제 모델의 판정 품질 검증이 아닙니다. 5분 이내에 적용하세요." : "샘플이 접수 기준을 통과하지 못했습니다."}{state.validation.issues?.map((issue, index) => <p key={index}><code>{issue.field}</code> · {issue.message} <small>({issue.type})</small></p>)}</div>}
          {selected.id !== catalog?.active_version_id && <div className="schema-activation"><h3>{rollback ? "이전 버전으로 복귀" : "운영 적용"}</h3><p><strong>{schemaVersionName(selected)}</strong>을 이후 새 접수에 적용합니다. Production API 정의서·다운로드·Swagger도 같은 기준으로 바뀝니다. 필수 필드 추가나 제한 강화로 기존 수집기의 새 요청이 거절될 수 있습니다. 기존 분석·접수된 테스트는 변경하지 않습니다.</p><label className="schema-check"><input type="checkbox" checked={state.acknowledged} disabled={blocked || !state.validation?.valid} onChange={event => controller.current?.acknowledge(event.target.checked)} />변경 비교와 수집기 영향을 확인했습니다.</label><button type="button" className="primary" disabled={!controller.current?.canActivate()} onClick={() => controller.current?.activate()}>{state.busy === "activate" ? "적용 중…" : rollback ? "검증한 이전 버전으로 복귀" : "검증한 버전 운영 적용"}</button></div>}
        </div>}
      </section>}
      {draft && <form className="panel schema-draft" onSubmit={async event => { event.preventDefault(); const saved = await controller.current?.save(draft); if (saved) setDraft(null); }}><h2>새 스키마 버전 작성</h2><p>기존 버전은 바꾸지 않고 이름·설명을 포함한 새 필드 정의를 저장합니다. 스키마 버전과 필드 정의 버전은 함께 고정됩니다.</p><fieldset disabled={busy}><label>버전 이름<input ref={draftName} value={draft.name} maxLength={120} required onChange={event => setDraft({ ...draft, name: event.target.value })} /></label><label>변경 설명<input value={draft.change_note} maxLength={1000} required onChange={event => setDraft({ ...draft, change_note: event.target.value })} /></label></fieldset>
        {draft.fields.map((field, index) => <FieldEditor key={index} field={field} index={index} defaults={catalog?.default_fields || []} disabled={busy} onChange={value => setDraft({ ...draft, fields: draft.fields.map((item, position) => position === index ? value : item) })} onRemove={() => setDraft({ ...draft, fields: draft.fields.filter((_, position) => position !== index) })} />)}
        <button type="button" className="secondary" disabled={busy || draft.fields.length >= 64} onClick={() => setDraft({ ...draft, fields: [...draft.fields, editSchemaField(newSchemaField())] })}>+ 필드 추가</button><p className="schema-help">하위 필드를 포함해 최대 64개·깊이 4단계·정의 64 KiB입니다. 허용값은 최대 50개이며 정규식·외부 참조·실행 코드는 지원하지 않습니다. 최종 제한은 서버에서 검사합니다.</p>
        <details><summary>복제 원본과 초안 변경 비교</summary>{draftFields ? <SchemaDiff before={selected?.fields} after={draftFields} beforeLabel="복제 원본" afterLabel="초안" /> : <p className="error">{draftError}</p>}</details>
        {draftError && <p className="error" role="alert">{draftError}</p>}<div className="schema-actions"><button type="submit" className="primary" disabled={blocked || Boolean(draftError)}>{state.busy === "save" ? "저장 중…" : "새 버전 저장"}</button><button type="button" className="secondary" disabled={busy} onClick={() => { if (window.confirm("저장하지 않은 초안을 버릴까요?")) setDraft(null); }}>작성 취소</button></div>
      </form>}
      </div>
    </div>
    <section className="panel"><h2>운영 적용 이력</h2><p className="schema-help">최근 100건 · 이전 버전 복귀도 별도 적용 이력으로 보존합니다.</p><div className="table-wrap"><table><thead><tr><th scope="col">시각</th><th scope="col">이전 버전</th><th scope="col">적용 버전</th><th scope="col">관리자</th><th scope="col">Revision</th></tr></thead><tbody>{state.history.map(item => <tr key={item.id}><td>{timestamp(item.created_at)}</td><td>{schemaVersionName(versions.find(version => version.id === item.previous_version_id))}</td><td>{schemaVersionName(versions.find(version => version.id === item.active_version_id))}</td><td>{item.actor_id}</td><td>{item.revision}</td></tr>)}</tbody></table>{!state.history.length && <p className="muted">{state.loading ? "불러오는 중…" : "표시할 적용 이력이 없습니다."}</p>}</div></section>
  </div>;
}

export function InputSchemaMetadata({ metadata }) {
  const [open, setOpen] = useState(false); const [version, setVersion] = useState(null); const [error, setError] = useState(""); const [attempt, setAttempt] = useState(0);
  useEffect(() => { setOpen(false); setVersion(null); setError(""); }, [metadata?.version_id]);
  useEffect(() => {
    if (!open || !metadata?.version_id) return;
    const request = new AbortController(); let current = true; setError(""); setVersion(null);
    api.inputSchema(metadata.version_id, { signal: request.signal }).then(value => { if (metadata.content_hash && value.content_hash !== metadata.content_hash) throw new Error("schema_hash_mismatch"); if (current) setVersion(value); }).catch(() => { if (current) setError("당시 필드 정의를 조회하지 못했거나 기록된 지문과 일치하지 않습니다."); });
    return () => { current = false; request.abort(); };
  }, [open, metadata?.version_id, metadata?.content_hash, attempt]);
  return <section className="schema-analysis-metadata"><h3>입력 스키마 · 접수 당시 기준</h3>{metadata ? <><p>v{metadata.version_number ?? "미기록"} · {metadata.field_count ?? "미기록"}개 필드 · {metadata.selection_origin === "ingest" ? "접수 시 고정" : metadata.selection_origin === "legacy_default" ? "이전 기본 기준" : metadata.selection_origin || "고정 시점 미기록"}</p><p className="schema-help">필드 정보는 실행 이력에만 기록하며, 설명을 LLM 입력에 추가하지 않습니다.</p><dl><dt>버전 ID</dt><dd>{metadata.version_id || "미기록"}</dd><dt>필드 정의 지문</dt><dd>{metadata.content_hash || "미기록"}</dd></dl>{metadata.version_id && <button type="button" className="secondary" aria-expanded={open} onClick={() => setOpen(value => !value)}>{open ? "당시 필드 정의 닫기" : "당시 필드 정의 보기"}</button>}{open && (error ? <div className="error" role="alert">{error}<button type="button" className="secondary" onClick={() => setAttempt(value => value + 1)}>다시 조회</button></div> : version ? <SchemaFields fields={version.fields} /> : <p role="status">필드 정의를 불러오는 중…</p>)}</> : <p>스키마 버전 미기록 · 이전 분석의 당시 정의를 현재 설정으로 추정하지 않습니다.</p>}</section>;
}
