import { useEffect, useRef, useState } from "react";
import { api } from "./api.js";
import HelpTooltip from "./HelpTooltip.jsx";
import Dialog from "./Dialog.jsx";
import { FIELD_TYPES, SAMPLE_EVENT, changeFieldType, createSchemaSettingsController, draftPayload, editSchemaField, emptySchemaSettingsState, newSchemaField, schemaDraft, schemaFieldDiff, schemaVersionName } from "./inputSchemaSettings.js";
import "./inputSchemaSettings.css";

const timestamp = value => value ? new Date(value).toLocaleString("ko-KR") : "미기록";
const fieldTypeNames = { string: "문자열", integer: "정수", number: "숫자", boolean: "참/거짓", object: "객체", array: "배열" };
const constraintNames = { min_length: "최소 글자 수", max_length: "최대 글자 수", minimum: "최솟값", maximum: "최댓값", min_items: "최소 항목 수", max_items: "최대 항목 수" };
export function SchemaFields({ fields = [] }) {
  const [nested, setNested] = useState(null);
  return <><div className="table-wrap schema-field-table"><table><caption className="sr-only">입력 필드 정의</caption><thead><tr><th scope="col">필드 / 설명</th><th scope="col">형식</th><th scope="col">필수 / 빈 값</th><th scope="col">제한</th></tr></thead><tbody>{fields.map(field => <tr key={field.name}><td><code>{field.name}</code><p>{field.description || "설명 없음"}</p></td><td>{fieldTypeNames[field.type] || field.type}</td><td>{field.required ? "필수" : "선택"}<br />{field.nullable ? "null 허용" : "null 불가"}</td><td>{Object.entries(constraintNames).filter(([key]) => field[key] != null).map(([key, label]) => <div key={key}>{label}: {field[key]}</div>)}{field.enum != null && <div>허용값: <code>{JSON.stringify(field.enum)}</code></div>}{(field.items || field.properties) && <button type="button" className="text-button" onClick={() => setNested(field)}>하위 필드 정의 보기</button>}</td></tr>)}</tbody></table></div>
    <Dialog open={Boolean(nested)} title="하위 필드 정의" onClose={() => setNested(null)} className="input-schema-settings schema-dialog">{nested && <><h3>{nested.name}</h3><pre className="schema-json">{JSON.stringify(nested.items || nested.properties, null, 2)}</pre></>}</Dialog>
  </>;
}
export function SchemaChangeContent({ change }) {
  return <div className="schema-diff-columns"><div><h4>변경 전</h4><pre>{change.before ? JSON.stringify(change.before, null, 2) : "필드 없음"}</pre></div><div><h4>변경 후</h4><pre>{change.after ? JSON.stringify(change.after, null, 2) : "필드 없음"}</pre></div></div>;
}
export function SchemaDiff({ before, after, beforeLabel = "현재 적용 버전", afterLabel = "선택한 버전" }) {
  const [selected, setSelected] = useState("");
  const changes = schemaFieldDiff(before, after), change = changes.find(item => item.name === selected);
  return <div className="schema-diff" aria-label="필드 정의 변경 비교"><p>{beforeLabel} → {afterLabel}</p>{changes.length ? <div className="schema-change-list">{changes.map(item => <button className="secondary" type="button" key={item.name} onClick={() => setSelected(item.name)}><span>{({ added: "추가", removed: "삭제", changed: "변경" })[item.kind]}</span> <code>{item.name}</code><span>변경 전후 보기</span></button>)}</div> : <p className="muted">필드 정의에 차이가 없습니다.</p>}
    <Dialog open={Boolean(change)} title="필드 변경 전후" onClose={() => setSelected("")} className="input-schema-settings schema-dialog">{change && <><h3>{change.name}</h3><SchemaChangeContent change={change} /></>}</Dialog>
  </div>;
}
function FieldEditor({ field, index, defaults, disabled, onChange, onRemove }) {
  const baseline = defaults.find(value => value.name === field.name);
  const [editing, setEditing] = useState(!baseline);
  const fieldName = field.name || `새 필드 ${index + 1}`;
  const numericKeys = field.type === "string" ? ["min_length", "max_length"] : ["integer", "number"].includes(field.type) ? ["minimum", "maximum"] : field.type === "array" ? ["min_items", "max_items"] : [];
  return <article className="schema-field-editor"><div className="schema-field-heading"><div><code>{fieldName}</code><small>{fieldTypeNames[field.type] || field.type} · {field.required ? "필수" : "선택"} · {baseline ? "기본 필드" : "추가 필드"}</small></div><button type="button" className="secondary small" disabled={disabled} aria-label={`${fieldName} 필드 편집`} onClick={() => setEditing(true)}>필드 편집</button></div><Dialog open={editing} title="필드 편집" onClose={() => setEditing(false)} className="input-schema-settings schema-dialog"><h3>{fieldName}</h3>{baseline && <p className="schema-help">기본 필드의 이름·형식과 최소 필수 조건은 유지합니다.</p>}<fieldset disabled={disabled}>
    <div className="schema-editor-grid"><label>필드명<input value={field.name} maxLength={64} readOnly={Boolean(baseline)} onChange={event => onChange({ ...field, name: event.target.value })} spellCheck={false} /></label><label>형식<select value={field.type} disabled={Boolean(baseline)} onChange={event => onChange(changeFieldType(field, event.target.value))}>{FIELD_TYPES.map(type => <option key={type} value={type}>{fieldTypeNames[type]}</option>)}</select></label>
      <label className="schema-full">설명<textarea rows={2} value={field.description} maxLength={1000} onChange={event => onChange({ ...field, description: event.target.value })} placeholder="필드가 나타내는 값과 수집 기준. 이 설명은 이력에만 기록합니다." /></label>
      <label className="schema-check"><input type="checkbox" checked={field.required} disabled={baseline?.required} onChange={event => onChange({ ...field, required: event.target.checked })} />필수</label><label className="schema-check"><input type="checkbox" checked={field.nullable} disabled={baseline?.nullable === false} onChange={event => onChange({ ...field, nullable: event.target.checked })} />null 허용<HelpTooltip label="null 허용">필드가 존재하지만 값이 null인 입력을 허용합니다. 필수 여부는 필드 자체를 생략할 수 있는지 정하므로 서로 다른 조건입니다.</HelpTooltip></label>
      {numericKeys.map(key => <label key={key}>{constraintNames[key]}<input type="number" step={field.type === "number" ? "any" : "1"} min={key.startsWith("min_") || key.startsWith("max_") ? 0 : undefined} value={field[key] ?? ""} onChange={event => onChange({ ...field, [key]: event.target.value })} placeholder="제한 없음" />{baseline?.[key] != null && <small>기본 경계 {baseline[key]}보다 완화할 수 없습니다.</small>}</label>)}
      {!["object", "array"].includes(field.type) && <label className="schema-full">허용값 · JSON 배열<input value={field._enum || ""} onChange={event => onChange({ ...field, _enum: event.target.value })} placeholder={'예: ["east", "west"] / [1, 2] · 빈칸이면 지정 안 함'} spellCheck={false} /></label>}
      {field.type === "object" && <label className="schema-full">하위 필드 · properties JSON 배열<textarea rows={6} value={field._properties || ""} onChange={event => onChange({ ...field, _properties: event.target.value })} placeholder={'[{"name":"region","description":"지역","type":"string","required":false,"nullable":true}]'} spellCheck={false} /><small>각 하위 필드도 이름·타입·필수·null·제한을 정의합니다. 등록하지 않은 하위 값은 보존합니다.</small></label>}
      {field.type === "array" && <label className="schema-full">배열 항목 · items JSON 객체<textarea rows={5} value={field._items || ""} onChange={event => onChange({ ...field, _items: event.target.value })} placeholder={'{"type":"string","nullable":false,"max_length":120}'} spellCheck={false} /><small>type·nullable·타입별 제한을 지정합니다. 객체 항목은 properties로 하위 필드를 정의합니다.</small></label>}
    </div><button type="button" className="secondary" disabled={Boolean(baseline)} onClick={onRemove}>필드 삭제</button>
  </fieldset><button type="button" className="secondary" onClick={() => setEditing(false)}>편집 내용 유지 · 닫기</button></Dialog></article>;
}

export default function InputSchemaSettings() {
  const [state, setState] = useState(emptySchemaSettingsState);
  const [draft, setDraft] = useState(null); const [sample, setSample] = useState("");
  const [discardOpen, setDiscardOpen] = useState(false);
  const [view, setView] = useState(""); const [draftOpen, setDraftOpen] = useState(false); const [draftCompareOpen, setDraftCompareOpen] = useState(false);
  const controller = useRef(null); const draftName = useRef(null);
  useEffect(() => { const instance = createSchemaSettingsController({ api, onChange: setState }); controller.current = instance; void instance.refresh(); return () => { instance.dispose(); controller.current = null; }; }, []);
  useEffect(() => { if (draft) { draftName.current?.focus(); draftName.current?.closest("form")?.scrollIntoView({ block: "start" }); } }, [Boolean(draft)]);
  const { catalog, selected, active } = state;
  const versions = catalog?.items || []; const busy = Boolean(state.busy); const blocked = busy || state.loading || state.needsRefresh || !catalog;
  let draftFields = null; let draftError = "";
  if (draft) { try { draftFields = draftPayload({ ...draft, name: draft.name || "미지정", change_note: draft.change_note || "미지정" }).fields; } catch (error) { draftError = error.message; } }
  const cloneVersion = () => { if (draft) { setDraftOpen(true); return; } controller.current?.clearValidation(); setDraft(schemaDraft(selected, catalog?.default_fields)); setDraftOpen(true); };
  const rollback = selected && active && selected.version_number < active.version_number;
  return <div className="page-stack input-schema-settings">
    <section className="panel schema-overview"><div className="schema-heading"><div><h2>입력 스키마</h2><p><span className="status purpose-production">적용 중</span> <strong>{catalog ? schemaVersionName(active) : "조회 중…"}</strong></p></div><div className="schema-actions"><button type="button" className="secondary" disabled={busy || state.loading} onClick={() => controller.current?.refresh()}>새로고침</button><button type="button" className="secondary" disabled={!catalog} onClick={() => setView("history")}>적용 이력</button></div></div></section>
    {state.error && <div className="error" role="alert">{state.error}</div>}{state.notice && <div className="notice" role="status">{state.notice}</div>}
    <div className="schema-layout"><section className="panel schema-version-list" aria-label="입력 스키마 저장 버전"><h2>저장 버전</h2>{versions.map(version => <button type="button" key={version.id} disabled={blocked || Boolean(draft)} aria-pressed={selected?.id === version.id} onClick={() => controller.current?.select(version.id)}><strong>{schemaVersionName(version)}</strong>{version.id === catalog.active_version_id && <span>운영 적용 중</span>}<small>{timestamp(version.created_at)}</small><small>{version.change_note}</small></button>)}{!versions.length && <p>{state.loading ? "불러오는 중…" : "저장 버전 없음"}</p>}</section>
      <div className="page-stack schema-workspace">{state.loading && <p className="loading" role="status">스키마 정의를 불러오는 중…</p>}{selected && !state.loading && <section className="panel"><div className="schema-heading"><div><h2>{schemaVersionName(selected)}</h2><p>{selected.fields.length}개 필드 · 저장된 버전</p></div><button type="button" className="primary" disabled={blocked} onClick={cloneVersion}>{draft ? "작성 중인 버전 열기" : "새 버전 작성"}</button></div><p>{selected.change_note}</p><div className="schema-actions"><button type="button" className="secondary" onClick={() => setView("compare")}>변경 비교</button><button type="button" className="secondary" disabled={blocked || Boolean(draft)} onClick={() => setView("validate")}>샘플 검증{selected.id !== catalog?.active_version_id ? " · 적용" : ""}</button><button type="button" className="text-button" onClick={() => setView("technical")}>기술정보</button></div><SchemaFields fields={selected.fields} />
      </section>}
      </div>
    </div>
    <Dialog open={view === "validate" && Boolean(selected)} title="샘플 검증 · 적용" onClose={() => { if (!busy) setView(""); }} className="input-schema-settings schema-dialog">{selected && <div className="schema-validation"><h3>{schemaVersionName(selected)}</h3><p>실제 원문·Cookie·API 키가 없는 예시 JSON 한 건을 입력하세요.<HelpTooltip label="샘플 검증">접수 기준만 확인합니다. LLM 호출·분석 접수·샘플 저장은 하지 않습니다. 숫자·boolean·객체·배열 추가 필드는 JSON 업로드를 사용하세요. CSV는 기존 포트만 숫자로 변환합니다.</HelpTooltip></p><label>검증할 샘플<textarea rows={10} value={sample} placeholder={SAMPLE_EVENT} disabled={busy} spellCheck={false} onChange={event => { controller.current?.clearValidation(); setSample(event.target.value); }} /></label><button type="button" className="secondary" disabled={blocked || !sample.trim()} onClick={() => controller.current?.validate(sample)}>{state.busy === "validate" ? "검증 중…" : "샘플 검증"}</button>
          {state.validation && <div role="status" className={state.validation.valid ? "notice" : "error"}>{state.validation.valid ? "샘플이 접수 기준을 통과했습니다. 이 검증은 실제 모델의 판정 품질 검증이 아닙니다. 5분 이내에 적용하세요." : "샘플이 접수 기준을 통과하지 못했습니다."}{state.validation.issues?.map((issue, index) => <p key={index}><code>{issue.field}</code> · {issue.message} <small>({issue.type})</small></p>)}</div>}
          {selected.id !== catalog?.active_version_id && <div className="schema-activation"><h3>{rollback ? "이전 버전으로 복귀" : "운영 적용"}</h3><p><strong>{schemaVersionName(selected)}</strong>을 이후 새 접수에 적용합니다. Production API 정의서·다운로드·Swagger도 같은 기준으로 바뀝니다. 필수 필드 추가나 제한 강화로 기존 수집기의 새 요청이 거절될 수 있습니다. 기존 분석·접수된 테스트는 변경하지 않습니다.</p><label className="schema-check"><input type="checkbox" checked={state.acknowledged} disabled={blocked || !state.validation?.valid} onChange={event => controller.current?.acknowledge(event.target.checked)} />변경 비교와 수집기 영향을 확인했습니다.</label><button type="button" className="primary" disabled={!controller.current?.canActivate()} onClick={() => controller.current?.activate()}>{state.busy === "activate" ? "적용 중…" : rollback ? "검증한 이전 버전으로 복귀" : "검증한 버전 운영 적용"}</button></div>}
        {state.error && <p className="error" role="alert">{state.error}</p>}</div>}</Dialog>
      <Dialog open={draftOpen && Boolean(draft)} title="새 스키마 버전 작성" onClose={() => { if (!busy) setDraftOpen(false); }} className="input-schema-settings schema-dialog">{draft && <form className="schema-draft" onSubmit={async event => { event.preventDefault(); const saved = await controller.current?.save(draft); if (saved) { setDraft(null); setDraftOpen(false); } }}><p className="schema-help">저장 후 샘플 검증을 거쳐 별도로 적용합니다.<HelpTooltip label="스키마 편집 범위">기본 11개 필드의 이름·타입·최소 필수 조건은 보호합니다. 추가 필드는 자유롭게 정의할 수 있지만 서버 제어값과 정답 필드는 등록할 수 없습니다. 미등록 벤더 값은 보존합니다.</HelpTooltip></p><p className="schema-safety-note">필드 설명은 공개 API 문서와 실행 이력에 기록하며 LLM 입력에는 추가하지 않습니다. 비밀값·실제 로그·개인정보를 넣지 마세요.</p><fieldset disabled={busy}><label>버전 이름<input ref={draftName} value={draft.name} maxLength={120} required onChange={event => setDraft({ ...draft, name: event.target.value })} /></label><label>변경 설명<input value={draft.change_note} maxLength={1000} required onChange={event => setDraft({ ...draft, change_note: event.target.value })} /></label></fieldset>
        {draft.fields.map((field, index) => <FieldEditor key={index} field={field} index={index} defaults={catalog?.default_fields || []} disabled={busy} onChange={value => setDraft({ ...draft, fields: draft.fields.map((item, position) => position === index ? value : item) })} onRemove={() => setDraft({ ...draft, fields: draft.fields.filter((_, position) => position !== index) })} />)}
        <button type="button" className="secondary" disabled={busy || draft.fields.length >= 64} onClick={() => setDraft({ ...draft, fields: [...draft.fields, editSchemaField(newSchemaField())] })}>+ 필드 추가</button><HelpTooltip label="필드 정의 한도">하위 필드를 포함해 최대 64개, 깊이 4단계, 정의 64 KiB, 허용값 50개입니다. 정규식·외부 참조·실행 코드는 지원하지 않으며 서버에서 최종 검사합니다.</HelpTooltip>
        <button type="button" className="secondary" onClick={() => setDraftCompareOpen(true)}>복제 원본과 초안 변경 비교</button><Dialog open={draftCompareOpen && draftOpen} title="스키마 초안 변경 비교" onClose={() => setDraftCompareOpen(false)} className="input-schema-settings schema-dialog">{draftFields ? <SchemaDiff before={selected?.fields} after={draftFields} beforeLabel="복제 원본" afterLabel="초안" /> : <p className="error">{draftError}</p>}</Dialog>
        {draftError && <p className="error" role="alert">{draftError}</p>}{state.error && <p className="error" role="alert">{state.error}</p>}<div className="schema-actions"><button type="submit" className="primary" disabled={blocked || Boolean(draftError)}>{state.busy === "save" ? "저장 중…" : "새 버전 저장"}</button><button type="button" className="secondary" disabled={busy} onClick={() => setDraftOpen(false)}>닫기 · 초안 유지</button><button type="button" className="text-button" disabled={busy} onClick={() => setDiscardOpen(true)}>초안 삭제</button></div>
      </form>}</Dialog>
    <Dialog open={discardOpen && draftOpen && Boolean(draft)} title="스키마 초안 삭제" onClose={() => setDiscardOpen(false)} className="input-schema-settings schema-dialog"><p>저장하지 않은 필드 정의와 초안 입력을 버립니다. 삭제한 초안은 복구할 수 없으며 저장된 스키마와 현재 접수 기준은 바뀌지 않습니다.</p><div className="schema-actions"><button type="button" className="secondary" onClick={() => setDiscardOpen(false)}>계속 작성</button><button type="button" className="primary" disabled={busy} onClick={() => { if (!busy) { setDraft(null); setDraftOpen(false); setDraftCompareOpen(false); setDiscardOpen(false); } }}>초안 삭제 확인</button></div></Dialog>
    <Dialog open={view === "history"} title="스키마 적용 이력" onClose={() => setView("")} className="input-schema-settings schema-dialog"><p className="schema-help">최근 100건</p><div className="table-wrap"><table><thead><tr><th scope="col">시각</th><th scope="col">이전 버전</th><th scope="col">적용 버전</th><th scope="col">관리자</th></tr></thead><tbody>{state.history.map(item => <tr key={item.id}><td>{timestamp(item.created_at)}</td><td>{schemaVersionName(versions.find(version => version.id === item.previous_version_id))}</td><td>{schemaVersionName(versions.find(version => version.id === item.active_version_id))}</td><td>{item.actor_id}</td></tr>)}</tbody></table>{!state.history.length && <p className="muted">{state.loading ? "불러오는 중…" : "표시할 적용 이력이 없습니다."}</p>}</div></Dialog>
    <Dialog open={view === "compare" && Boolean(selected)} title="현재 적용 버전과 비교" onClose={() => setView("")} className="input-schema-settings schema-dialog">{selected && <SchemaDiff before={active?.fields} after={selected.fields} beforeLabel={schemaVersionName(active)} afterLabel={schemaVersionName(selected)} />}</Dialog>
    <Dialog open={view === "technical" && Boolean(selected)} title="스키마 기술정보" onClose={() => setView("")} className="input-schema-settings schema-dialog">{selected && <dl className="schema-identifiers"><dt>버전 ID</dt><dd>{selected.id}</dd><dt>필드 정의 지문</dt><dd>{selected.content_hash}</dd><dt>등록자 / 시각</dt><dd>{selected.created_by} · {timestamp(selected.created_at)}</dd><dt>복제 원본</dt><dd>{selected.parent_id || "기본 버전"}</dd></dl>}</Dialog>
  </div>;
}

export function InputSchemaMetadata({ metadata }) {
  const [open, setOpen] = useState(false); const [version, setVersion] = useState(null); const [error, setError] = useState(""); const [attempt, setAttempt] = useState(0);
  useEffect(() => { setOpen(false); setVersion(null); setError(""); }, [metadata?.version_id]);
  useEffect(() => {
    if (!open || !metadata?.version_id) return;
    const request = new AbortController(); let current = true; setError(""); setVersion(null);
    api.inputSchema(metadata.version_id, { signal: request.signal }).then(value => { if (metadata.content_hash && value.content_hash !== metadata.content_hash) throw new Error("schema_hash_mismatch"); if (current) setVersion(value); }).catch(() => { if (current) setError("당시 필드 정의를 조회하지 못했거나 기록된 지문과 일치하지 않습니다."); });
    return () => { current = false; request.abort(); };
  }, [open, metadata?.version_id, metadata?.content_hash, attempt]);
  return <section className="schema-analysis-metadata"><h3>입력 스키마 · 접수 당시 기준</h3>{metadata ? <><p>v{metadata.version_number ?? "미기록"} · {metadata.field_count ?? "미기록"}개 필드 · {metadata.selection_origin === "ingest" ? "접수 시 고정" : metadata.selection_origin === "legacy_default" ? "이전 기본 기준" : metadata.selection_origin || "고정 시점 미기록"}</p><p className="schema-help">필드 정보는 실행 이력에만 기록하며, 설명을 LLM 입력에 추가하지 않습니다.</p><dl><dt>버전 ID</dt><dd>{metadata.version_id || "미기록"}</dd><dt>필드 정의 지문</dt><dd>{metadata.content_hash || "미기록"}</dd></dl>{metadata.version_id && <button type="button" className="secondary" aria-expanded={open} onClick={() => setOpen(value => !value)}>{open ? "당시 필드 정의 닫기" : "당시 필드 정의 보기"}</button>}{open && (error ? <div className="error" role="alert">{error}<button type="button" className="secondary" onClick={() => setAttempt(value => value + 1)}>다시 조회</button></div> : version ? <SchemaFields fields={version.fields} /> : <p role="status">필드 정의를 불러오는 중…</p>)}</> : <p>스키마 버전 미기록 · 이전 분석의 당시 정의를 현재 설정으로 추정하지 않습니다.</p>}</section>;
}
