import assert from "node:assert/strict";
import { OPENAI_BASE_URL, EXTERNAL_DATA_APPROVAL, changeProfileProvider, editProfileForm, modelProfileError, newProfileForm, profilePayload, profileRequiresKey, providerLabel, providerOf, validateProfileForm } from "./llmProfiles.js";

const internal = { ...newProfileForm(), id: "synthetic-vllm", name: "synthetic-vllm", has_api_key: true };
assert.equal(providerOf({}), "vllm");
assert.equal(providerLabel({}), "vLLM");
assert.equal(providerLabel({ provider: "openai" }), "OpenAI");
assert.equal(providerLabel({ provider: "unexpected" }), "알 수 없는 공급자");
assert.equal(newProfileForm().context_window, 32768);
assert.equal(newProfileForm().base_url, "");
assert.equal(newProfileForm().model_name, "google/gemma-4-26B-A4B-it");
assert.notEqual(newProfileForm(), newProfileForm());
assert.equal(newProfileForm().external_data_approved, false);

const edited = editProfileForm({ ...internal, api_key: "synthetic-response-secret", extra: "never-copy", provider: undefined });
assert.equal(edited.api_key, "");
assert.equal(edited.extra, undefined);
assert.equal(edited.provider, "vllm");
assert.equal(profilePayload(edited, internal).api_key, undefined);
assert.equal(Object.hasOwn(profilePayload(edited, internal), "api_key"), false);
assert.equal(profilePayload({ ...edited, api_key: "synthetic-replacement" }, internal).api_key, "synthetic-replacement");

const switched = changeProfileProvider({ ...edited, api_key: "synthetic-vllm-secret", base_url: "http://synthetic.internal:8000/v1" }, "openai");
assert.equal(switched.base_url, OPENAI_BASE_URL);
assert.equal(switched.model_name, "");
assert.equal(switched.api_key, "");
assert.equal(switched.tls_verify, true);
assert.equal(switched.external_data_approved, false);
assert.equal(switched.key_reset_required, true);
assert.equal(switched.context_window, edited.context_window);
assert.equal(profileRequiresKey(switched, internal), true);
assert.match(validateProfileForm(switched, internal), /모델 이름/);

const openai = { ...switched, name: "synthetic-openai", model_name: "synthetic-model" };
assert.match(validateProfileForm(openai, null), /승인/);
assert.match(validateProfileForm({ ...openai, external_data_approved: true }, internal), /새 API Key/);
assert.match(validateProfileForm({ ...openai, api_key: "   ", external_data_approved: true }, null), /새 API Key/);
const valid = { ...openai, api_key: "synthetic-openai-secret", external_data_approved: true };
assert.equal(validateProfileForm(valid, internal), "");
const payload = profilePayload({ ...valid, base_url: "https://untrusted.invalid/v1", tls_verify: false }, internal);
assert.equal(payload.base_url, OPENAI_BASE_URL);
assert.equal(payload.tls_verify, true);
assert.equal(payload.external_data_approved, true);
assert.equal(payload.api_key, "synthetic-openai-secret");
assert.equal(payload.key_reset_required, undefined);
assert.equal(payload.id, undefined);
assert.equal(EXTERNAL_DATA_APPROVAL.includes("payload·Cookie"), true);

const existingOpenai = { ...valid, id: "synthetic-openai", has_api_key: true, thinking_enabled: null };
const openaiEdit = editProfileForm(existingOpenai);
assert.equal(openaiEdit.api_key, "");
assert.equal(openaiEdit.key_reset_required, false);
assert.equal(openaiEdit.external_data_approved, true);
assert.equal(profileRequiresKey(openaiEdit, existingOpenai), false);
assert.equal(validateProfileForm(openaiEdit, existingOpenai), "");
assert.equal(Object.hasOwn(profilePayload(openaiEdit, existingOpenai), "api_key"), false);
assert.equal(profileRequiresKey(openaiEdit, { ...existingOpenai, has_api_key: false }), true);
assert.equal(profileRequiresKey(openaiEdit, null), true);
assert.equal(profileRequiresKey(changeProfileProvider(changeProfileProvider(openaiEdit, "vllm"), "openai"), existingOpenai), true);

const backToInternal = changeProfileProvider(valid, "vllm");
assert.equal(backToInternal.external_data_approved, false);
assert.equal(backToInternal.api_key, "");
assert.equal(backToInternal.base_url, newProfileForm().base_url);
assert.equal(backToInternal.model_name, newProfileForm().model_name);
assert.equal(profileRequiresKey(backToInternal, existingOpenai), false);
assert.equal(profilePayload(backToInternal, existingOpenai).api_key, "");
assert.equal(profilePayload({ ...backToInternal, external_data_approved: true }, existingOpenai).external_data_approved, false);
assert.equal(changeProfileProvider(valid, "openai"), valid);
assert.equal(changeProfileProvider(valid, "unexpected"), valid);
assert.match(validateProfileForm({ ...valid, name: "잘못된 이름" }, null), /프로필 이름/);
assert.match(validateProfileForm({ ...valid, max_output_tokens: "32768" }, null), /Context window/);
assert.equal(typeof profilePayload({ ...edited, timeout_seconds: "60" }, internal).timeout_seconds, "number");
const internalTargets = { items: [{ id: "synthetic-target", ip_address: "10.0.0.10", port: 8000 }], loading: false, error: "" };
const literalProfile = { ...internal, base_url: "http://10.0.0.10:8000/v1" };
assert.match(validateProfileForm(literalProfile, internal), /불러오는 중/);
assert.match(validateProfileForm(literalProfile, internal, { items: [] }), /먼저 등록/);
assert.match(validateProfileForm(literalProfile, internal, { ...internalTargets, error: "조회 실패" }), /확인하지 못/);
assert.match(validateProfileForm({ ...literalProfile, base_url: "http://vllm.internal:8000/v1" }, internal, internalTargets), /hostname/);
assert.match(validateProfileForm({ ...literalProfile, base_url: "http://10.0.0.10:8001/v1" }, internal, internalTargets), /등록되어 있지/);
assert.equal(validateProfileForm(literalProfile, internal, internalTargets), "");
assert.equal(validateProfileForm(valid, internal, { items: null, error: "조회 실패" }), "");
assert.match(modelProfileError(new Error("vllm_target_not_allowed")), /Internal Egress/);
assert.match(modelProfileError(new Error("vllm_base_url_must_use_ip_address")), /hostname 대신 IP 주소/);
assert.equal(modelProfileError(new Error("existing_profile_error")), "existing_profile_error");
console.log("LLM profile provider switching, credential isolation, approval, editing and payload tests passed.");
