import NavigationAction from "./NavigationAction.jsx";
import { useR5Words } from "./R5Evaluation.jsx";
import TestDefaults from "./R5TestDefaults.jsx";

export default function SetupProgress({ setup, onNavigate, onPromotion }) {
  const w = useR5Words(); if (!setup) return null;
  const names = { model_connection: ["모델 연결", "Connect a model"], test_configuration: ["기본 테스트 설정", "Default Test Configuration"], ground_truth_published: ["정답 데이터 공식 버전", "Published Ground Truth"], official_candidate_test: ["공식 테스트", "Official Test"], first_promotion: ["첫 운영 반영", "First Production application"] };
  const states = { not_started: ["시작 전", "Not started"], in_progress: ["진행 중", "In progress"], needs_attention: ["확인 필요", "Needs attention"], ready: ["완료", "Ready"], unknown: ["확인할 수 없음", "Unknown"] };
  const destination = { model_connection: "profiles", ground_truth_published: "groundTruth", official_candidate_test: "run", first_promotion: "runs" };
  const next = setup.next_action?.kind || Object.keys(names).find(key => setup.steps[key].state !== "ready");
  const actionNames = { model_connection: ["LLM 프로필 열기", "Open LLM Profiles"], ground_truth_published: ["정답 데이터 열기", "Open Ground Truth"], official_candidate_test: ["새 테스트", "New Test"], first_promotion: ["운영 반영 검토", "Production Review"] };
  return <>{setup.production_state === "unconfigured" && <section className="panel r5-setup"><h2>{w("첫 운영 설정", "Set up Production")}</h2><p className="v5-context">{w("검증한 테스트 설정을 운영에 반영합니다. 각 단계를 완료해도 다음 단계는 자동 실행되지 않습니다.", "Apply a tested configuration to Production. Completing a step never automatically starts the next.")}</p><ol>{Object.entries(names).map(([key, label], index) => { const step = setup.steps[key]; return <li key={key}><strong>{index + 1}</strong><span>{w(...label)}{key === "official_candidate_test" && step.total != null && <small> · {step.processed} / {step.total}{step.warning_count > 0 && ` · ${w("실패·거부", "Failed or rejected")} ${step.warning_count}`}</small>}</span><span className="r5-state">{w(...(states[step.state] || states.unknown))}</span>{key === "test_configuration" ? <TestDefaults primary={next === key} /> : <button className={next === key ? "primary" : "secondary"} onClick={() => key === "first_promotion" && setup.steps.official_candidate_test.test_run_id ? onPromotion(setup.steps.official_candidate_test.test_run_id) : onNavigate(destination[key])}>{w(...actionNames[key])} →</button>}</li>; })}</ol><small className="v5-context">{w("문항 실패가 있는 테스트는 완료 기록과 별개로 운영 반영 조건을 충족하지 못할 수 있습니다.", "A completed evaluation with case failures can still be blocked from Production.")}</small></section>}
    {setup.production_state === "legacy_active" && <section className="panel r5-legacy-banner"><h2>{w("기존 운영 설정 유지 중", "Legacy Production configuration retained")}</h2><p className="v5-context">{w("현재 운영은 그대로 유지됩니다. 다음 변경부터 공식 테스트와 운영 반영 검토를 거칩니다.", "Current Production is unchanged. Future changes require an Official Test and Production Review.")}</p><NavigationAction onClick={() => onNavigate("runs")}>{w("테스트 열기", "Open Tests")}</NavigationAction></section>}
    {setup.drifted && <p className="notice">{w("현재 설정과 마지막 운영 반영 기록이 다릅니다. 설정과 변경 이력을 확인하세요.", "Current settings differ from the last Production application. Review configuration and activity.")}</p>}
    <p className="v5-context">{w("운영 API 키", "Production API credentials")}: {setup.production_api_credentials === "ready" ? w("준비됨", "Ready") : w("발급 필요", "Missing")} · {w("실제 요청", "Observed traffic")}: {setup.production_api_traffic.status === "observed" ? w("수신 확인", "Observed") : w("아직 없음", "Not yet observed")}{setup.production_api_traffic.since && ` · ${w("최근 운영 반영 이후", "Since the latest Production application")}`}</p>
  </>;
}
