import { useEffect, useRef, useState } from "react";
import { api } from "./api.js";
import Dialog from "./Dialog.jsx";
import DataTable from "./DataTable.jsx";
import Pagination from "./Pagination.jsx";
import { useR5Words } from "./R5Evaluation.jsx";
import { newTestRequestKey } from "./testRuns.js";

export default function TestGroundTruthImport({ runId, open, onClose, onOpenDataset, itemIds }) {
  const w = useR5Words();
  const [target, setTarget] = useState("create_new_dataset"), [name, setName] = useState(""), [datasetId, setDatasetId] = useState("");
  const [catalog, setCatalog] = useState(null), [query, setQuery] = useState(""), [catalogOffset, setCatalogOffset] = useState(0), [preview, setPreview] = useState(null), [result, setResult] = useState(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [category, setCategory] = useState(""), [offset, setOffset] = useState(0);
  const inFlight = useRef(false), requestKey = useRef(null);
  useEffect(() => { if (!open || target !== "append_to_existing_dataset") return; const controller = new AbortController(); const timer = setTimeout(() => api.searchValidationDatasets({ query, offset: catalogOffset, limit: 20 }, { signal: controller.signal }).then(value => { if (!controller.signal.aborted) setCatalog(value); }).catch(() => { if (!controller.signal.aborted) setError(w("데이터셋을 불러오지 못했습니다.", "Could not load datasets.")); }), 180); return () => { clearTimeout(timer); controller.abort(); }; }, [open, target, query, catalogOffset]);
  function resetPreview() { setPreview(null); setError(""); setResult(null); requestKey.current = null; setOffset(0); }
  async function inspect(event) { event.preventDefault(); if (inFlight.current) return; inFlight.current = true; setBusy(true); setError("");
    try { const working = target === "append_to_existing_dataset" ? await api.workingDataset(datasetId) : null;
      const value = await api.previewTestImport(runId, { target, ...(itemIds ? { test_run_item_ids: itemIds } : {}), ...(working ? { dataset_id: datasetId, expected_working_revision: working.working_revision } : { new_dataset_name: name.trim() || null }) }); setPreview(value); requestKey.current = newTestRequestKey(); }
    catch (e) { setError(e.status === 409 ? w("테스트 또는 데이터셋이 변경됐습니다. 다시 확인하세요.", "The Test or dataset changed. Please refresh the preview.") : w("사례를 확인하지 못했습니다.", "Could not inspect the cases.")); }
    finally { inFlight.current = false; setBusy(false); }
  }
  async function confirm() { if (inFlight.current || !preview || result) return; inFlight.current = true; setBusy(true); setError("");
    try { setResult(await api.confirmTestImport(runId, { preview_token: preview.preview_token, idempotency_key: requestKey.current })); }
    catch (e) { if (e.status === 409) setPreview(null); setError(e.status === 409 ? w("미리보기가 만료되었거나 내용이 변경됐습니다. 다시 확인하세요.", "The preview expired or changed. Please inspect again.") : w("저장을 확인하지 못했습니다. 같은 요청으로 다시 시도할 수 있습니다.", "Could not confirm the save. Retry uses the same request.")); }
    finally { inFlight.current = false; setBusy(false); }
  }
  const categories = { new: w("새 문항", "New case"), duplicate: w("중복", "Duplicate"), reference_conflict: w("답안 충돌", "Reference conflict"), missing_reference: w("참고 라벨 없음", "Missing Reference Label"), unavailable: w("가져올 수 없음", "Unavailable") };
  const entries = preview?.items.filter(row => !category || row.category === category) || [];
  return <Dialog open={open} title={w("테스트 사례를 정답 데이터에 추가", "Add Test Cases to Ground Truth")} onClose={() => { if (!inFlight.current) onClose(); }}><div className="data-form"><p className="v5-context">{w("공식 버전의 정답, 없으면 접수 당시 참고 라벨을 가져옵니다. 심층 판정은 정답으로 사용하지 않습니다. 저장 후에도 공식 버전은 따로 만들어야 합니다.", "Uses the published Ground Truth, then the fixed Reference Label. Deep Assessment is never used as an answer. Publishing remains a separate action.")}</p>
    {result ? <div role="status"><h3>{w("편집 중 데이터에 추가했습니다.", "Cases added to Draft.")}</h3><p>{w(`추가 ${result.added} · 중복 ${result.duplicates} · 충돌 ${result.conflicts}`, `Added ${result.added} · duplicates ${result.duplicates} · conflicts ${result.conflicts}`)}</p><button className="primary" onClick={() => { onClose(); onOpenDataset?.(result.dataset_id); }}>{w("정답 데이터 열기", "Open Ground Truth")}</button></div> : <><form className="data-form" onSubmit={inspect}><label>{w("저장 위치", "Destination")}<select value={target} disabled={busy} onChange={e => { setTarget(e.target.value); resetPreview(); }}><option value="create_new_dataset">{w("새 데이터셋 만들기", "Create new dataset")}</option><option value="append_to_existing_dataset">{w("기존 데이터셋에 추가", "Append to existing dataset")}</option></select></label>
    {target === "create_new_dataset" ? <label>{w("데이터셋 이름", "Dataset name")}<input maxLength={120} value={name} disabled={busy} placeholder={w("비워두면 테스트명 사용", "Defaults to Test name")} onChange={e => { setName(e.target.value); resetPreview(); }} /></label> : <><label>{w("데이터셋 검색", "Find dataset")}<input disabled={busy} value={query} onChange={e => { setQuery(e.target.value); setCatalogOffset(0); }} /></label><label>{w("데이터셋", "Dataset")}<select required value={datasetId} disabled={busy} onChange={e => { setDatasetId(e.target.value); resetPreview(); }}><option value="">{w("선택하세요", "Choose dataset")}</option>{catalog?.items.map(row => <option key={row.id} value={row.id}>{row.name} · {row.total} {w("문항", "cases")}</option>)}</select></label>{catalog && <Pagination total={catalog.total} limit={20} offset={catalogOffset} onOffsetChange={setCatalogOffset} disabled={busy} label={w("데이터셋 페이지", "Dataset pages")} />}</>}
    <button className="secondary" disabled={busy || target === "append_to_existing_dataset" && !datasetId}>{w("미리보기", "Preview")}</button></form>
    {preview && <><div className="r5-import-summary">{[[w("전체", "Total"), preview.source_total], [w("추가", "New"), preview.new_count], [w("중복", "Duplicates"), preview.duplicate_count], [w("답안 충돌", "Conflicts"), preview.reference_conflict_count], [w("참고 라벨 없음", "Missing reference"), preview.missing_reference_count], [w("가져올 수 없음", "Unavailable"), preview.unavailable_count]].map(([label, count]) => <span key={label}>{label}<strong>{count}</strong></span>)}</div><label>{w("문항 구분", "Category")}<select value={category} onChange={e => { setCategory(e.target.value); setOffset(0); }}><option value="">{w("전체", "All")}</option>{Object.entries(categories).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><DataTable label={w("가져올 문항 미리보기", "Import preview")} data={entries.slice(offset, offset + 10)} getRowId={row => row.test_run_item_id} columns={[{ id: "name", header: w("문항", "Case"), render: row => row.case_name || `${w("문항", "Case")} ${row.row_number}` }, { id: "category", header: w("상태", "Status"), render: row => categories[row.category] }]} /><Pagination total={entries.length} limit={10} offset={offset} onOffsetChange={setOffset} label={w("미리보기 페이지", "Preview pages")} /><p className="v5-context">{w("충돌한 기존 답안은 덮어쓰지 않고 확인 필요로 표시합니다. 참고 라벨이 없는 문항도 확인 필요로 추가합니다.", "Conflicts do not overwrite existing answers. Conflicts and missing Reference Labels need attention.")}</p><button className="primary" disabled={busy || !preview.importable} onClick={confirm}>{busy ? w("저장 중…", "Saving…") : w("편집 중 데이터에 추가", "Add to Draft")}</button></>}
    </>}{error && <p className="error" role="alert">{error}</p>}</div></Dialog>;
}
